apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-kubeconfig
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /workspace/kubeconfig/ca.crt
        extensions:
        - extension:
            last-update: Tue, 12 Jul 2022 10:05:02 JST
            provider: minikube.sigs.k8s.io
            version: v1.26.0
          name: cluster_info
        server: https://192.168.49.2:8443
      name: minikube
    contexts:
    - context:
        cluster: minikube
        extensions:
        - extension:
            last-update: Tue, 12 Jul 2022 10:05:02 JST
            provider: minikube.sigs.k8s.io
            version: v1.26.0
          name: context_info
        namespace: default
        user: minikube
      name: minikube
    current-context: minikube
    kind: Config
    preferences: {}
    users:
    - name: minikube
      user:
        client-certificate: /workspace/kubeconfig/client.crt
        client-key: /workspace/kubeconfig/client.key
  client.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDITCCAgmgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIyMDcwNzEyMDMxM1oXDTI1MDcwNzEyMDMxM1owMTEXMBUGA1UE
    ChMOc3lzdGVtOm1hc3RlcnMxFjAUBgNVBAMTDW1pbmlrdWJlLXVzZXIwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5QtboZfhJEBM/A7ikCnaZsQvvv80W
    98YiMm5i7xTBBPkbdPn6pt38EgXYiDt/gOdW1ng9b9FHwOpg9fuVIAuTRMXR0Ate
    7D0neEnoyA0a4rqa5DxYJnRLaz1VCjLSZcosupqhhsCTOOGr4xRwXwUDfz+JdciQ
    KEaqjwT/6fVsmGtxAzLEfa88pifsA6JJgBf/T5OriWmOwnZXUgy+8+yNH8WNrQcb
    v8svKutVE2q+mzYZTzVqITX53WMpx5BV1zCvzcyqoqml43WU0jWFS1TWGJuRo0J2
    u5lZW4BWFrMvUeCyeMwpYYa2jZxh52lPoeyzR5hEGLMY2jHjFukj8KArAgMBAAGj
    YDBeMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRTPvxj06v/T5QJrCZxJEWizCsT
    5jANBgkqhkiG9w0BAQsFAAOCAQEAYStwkFw1nDNsh7wDvvb3JWa9nXjf+QE73cZ7
    QrcbQqcFl4r5tvAWL3L+7rwg0xv5H+6YbsMyWyENlmhC3faZP4mvOVoL7LTYz0LJ
    Ak5U3EER2kVTHYD9WLX8LCe57lF0rytuyBynDpH8hszz43OgonMURuW76+vdFBcE
    J+GJoDSHUIx1qNxcYaXkfkPqrs5uRfLBFNSc1rcfRG9VLO5UcsSWYxdUAxL0Vg+X
    8mic0/EpTFvmJ9dFKg874QQXj2ZCDRtdSXXcqXhR5j4/2jv64O/taZm5liUT01/R
    EJeBd5Qi7OrgqtSCqPWImanOLQMbBMfi4fL5ReUCuBYRQ2oUIw==
    -----END CERTIFICATE-----
  client.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAuULW6GX4SRATPwO4pAp2mbEL77/NFvfGIjJuYu8UwQT5G3T5
    +qbd/BIF2Ig7f4DnVtZ4PW/RR8DqYPX7lSALk0TF0dALXuw9J3hJ6MgNGuK6muQ8
    WCZ0S2s9VQoy0mXKLLqaoYbAkzjhq+MUcF8FA38/iXXIkChGqo8E/+n1bJhrcQMy
    xH2vPKYn7AOiSYAX/0+Tq4lpjsJ2V1IMvvPsjR/Fja0HG7/LLyrrVRNqvps2GU81
    aiE1+d1jKceQVdcwr83MqqKppeN1lNI1hUtU1hibkaNCdruZWVuAVhazL1HgsnjM
    KWGGto2cYedpT6Hss0eYRBizGNox4xbpI/CgKwIDAQABAoIBAB+/e5LB/sWOkq3G
    1nqOLHr0I0aHyP65oWO03sPnktftIT96UWiJ9hq/f+72kbOtBHgWMu7cXbH9Nm09
    WkrY/gLT0068Z2Zx95zu+UOCHPTRjAcFO+4jUOSn0Q/kuobh2L7Hj75EmHXiVpId
    TSBguDw8L0hAPgmuTUXnUoUEtAFS5m5f4RdoCeUG/2xPqkT0er9pCbrAVErBghGX
    DqT9sJev76M1MHkdnr90iE0/F3hvinXDzKn0iwH7/V3dxIwBTJGjFK3eWvLVjyw+
    k5H8sT4hjQlIb4c7o1QHOgl/hnIwJs7q1Uj6RW0IAx/F1Huj5EBBvwl/VeoVnr/N
    ZFnxTrkCgYEA8jPa2sK/vwGhagCX+gR3BR32Jti7WZpXQ6zFFocyHh2nimpzel8o
    4xCfd6uL3YyE8NbZsopYBK1zpd+ab+/NQRgGgRtM55lczKrKYgceqx3mLrfpbZ68
    nD21FLRzhESUfsGwJaDxqSVFHwnKm3kxHABZ2yWvWrxaz9V4QyzEWK0CgYEAw9CV
    Gzs5v7NT9rchBC8XKtEInfMOowr3dCa60W1Wl7iajSuMb6rUroRcAAh1L50yLD9g
    PA8CrhV6vFvFLR9y+wl13hqg79xT64uxE4IuI6v2FeUct2Dqh5boXLUi5k04IO4r
    r6HRHldgVCMvjsdR1zEd2ayXoWgcQWcJngaLPzcCgYEAq+33e7cnWjWUGaVWPNqS
    ioVcSPMs+0w+igHI3lcWUp6GYhFy6/lFEvqn2NFjtd+cN0KswrrGBHwETklOXguC
    TqT5aQiyLO2HHJpYlAGt2Zad4agYAgLerKJ5OrtmDQyJxPlFS1DWe1XDnWbb9kWv
    gMsW/iPgOK7gYAyPFFBhCPkCgYEAwYUlp1j79LIE/CH2Nk1Xxw/5RSiOQaI39onE
    Pe+iEaX20CfGziF1udfDmKDDN8BScppbwF9RVbySpQ7JKpQXLXQnEc8dWJBWO8a9
    xTr14Hk1ZmQc4jqc7k287MpzaEnOe/UGJbh1lFfkMqLngGMKRfMbviGtZW4f5p8v
    SQbMnTcCgYBHDXKPPwdtdDImyV0B7N2eqpE+MOhdbY9zn8pJIihaBD5DTSQz2afR
    k2Z0ARukWoD31FUrFEAjzs3bU9O88+ZFVLnx1aiohmhp6fM7Ydzc7aa6pQSJtEz+
    z2KlGFNWk1iWCYRUf0tUrehytlZiP//MxI8OYbHDErxEhEYgRkPmqA==
    -----END RSA PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIyMDcwNzEyMDMxM1oXDTMyMDcwNTEyMDMxM1owFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN2H
    NDhVMXnxF/LX+ZAkigfCpxkYqpiacI6AfbX0FBSQ+t3iMSTUL8GL9jxNm/DEY7XI
    UJW4dIsyNPYNcE3xSbo3Yula6FKzYCqhFiOxrfsd44zsYqpGFw7n/MTrNp0YdGNz
    +h52Imc1xZzLW+Ae2ZjdIQAMNK+bkCghl3xrZSuOsD0PZrpz+Vr+AovKK3IDFShp
    lCOXLkwn0bVN1XGb4LORougkHnbbLW0fy9mXfGEWagMAqN+hZHMy7xcQ1s/E/jxB
    ECUMDhH+jA7ybqOKDWevqJ18aI8EZ4JRQggs1VHKzjP3Nx1xINX3vhUNv6hexLDq
    H+NBqv6WpKUYS24cdEsCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBRTPvxj06v/T5QJrCZxJEWizCsT5jANBgkqhkiG9w0BAQsFAAOCAQEAjh+HS639
    ugP3lXH1UkT9xiPprMvsvBzrJER0Dz0jQdbJcNSKDTEuPc9te17qp3jrjzb4yILB
    fojnvVDWQDCu0uoNCYroA3CWEIkCnzQwTCAJgHuWIH6cRdYMm//J26aNe4gtXjJN
    QNkMlhLZtbBL8Wv465FMDYfrkSW3Pe6cX4KND8vpLsYNVzZlguPKSsYD8/iYFMjL
    ajwcUm0NrPDX9LIgGVwKi3oMzVPNrFl8iiWh+Fk8NKTEbNdjmJct9nCZ1HH4XJC+
    3eAvh+0AmcUpRb3zDllnugS3pcTRzEXOJuJVwdpL4JUHPipqGZsZcN5znSOfp4rX
    MCe8XGIjaT1abA==
    -----END CERTIFICATE-----
